---
# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build-vagrant-infrastructure:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Installing vagrant"
        run: ./.github/vagrant.sh

      - name: "Installing ansible"
        shell: bash
        run: ./.github/ansible.sh

      - name: "Run infrastructure"
        shell: bash
        run: |
          cd ./vagrant_haproxy_tcp_nginx_ansible/
          vagrant up

      - name: "Run ansible"
        shell: bash
        run: |
          ansible-playbook -i ./vagrant_haproxy_tcp_nginx_ansible/ansible/inventories/inventory-v2.yaml ./vagrant_haproxy_tcp_nginx_ansible/ansible/playbook-vms-v2.yaml

      - name: "Destroy infrastructure"
        shell: bash
        run: |
          vagrant destroy
